CREATE DATABASE QLKHACHSAN
GO

USE QLKHACHSAN
GO

CREATE TABLE DMSANPHAM
(
	MA VARCHAR(10) PRIMARY KEY,
	TENSANPHAM NVARCHAR(150)

)
GO
--------------------------------
CREATE TABLE DMKHACHHANG
(
	MA VARCHAR(10) PRIMARY KEY,
	TEN NVARCHAR(150),
	DIACHI NVARCHAR(150) ,
	SDT NCHAR(10),
	EMAIL NVARCHAR(150) ,
	GHICHU NVARCHAR(150)
)
GO

-----------------------------------
CREATE TABLE DMGIAPHONG
(

	MA VARCHAR(10) PRIMARY KEY,
	TGIANAPDUNG NVARCHAR(150) ,
	GIA FLOAT ,
	GHICHU NVARCHAR(150),	
)
GO

CREATE TABLE DMLOAIPHONG
(
	MA VARCHAR(10)PRIMARY KEY,
	TENLOAIPHONG NVARCHAR(150),
	SONGUOI INT,
	MOTA NVARCHAR(150)
)
GO


CREATE TABLE DMPHONG
(
	
	MA VARCHAR(10) PRIMARY KEY,
	MASANPHAM VARCHAR(10),
	MALOAIPHONG VARCHAR(10),
	TINHTRANG NVARCHAR(200),
	GHICHU NVARCHAR(150),
	FOREIGN KEY (MALOAIPHONG) REFERENCES DMLOAIPHONG(MA),
	FOREIGN KEY (MASANPHAM) REFERENCES DMSANPHAM(MA)
)
GO


CREATE TABLE DATPHONGCT
(
	
	MAPHONG VARCHAR(10) ,
	MAKHACHHANG VARCHAR(10),
	SLNGUOI INT ,
	NGAYDEN DATETIME2 ,
	NGAYDI DATETIME2,
	PRIMARY KEY (MAPHONG,MAKHACHHANG),
	FOREIGN KEY (MAPHONG) REFERENCES DMPHONG(MA),
	FOREIGN KEY (MAKHACHHANG) REFERENCES DMKHACHHANG(MA)
)
GO

--------------------------------------
CREATE TABLE DMDICHVU
(
	
	MA VARCHAR(10) PRIMARY KEY,
	MASANPHAM VARCHAR(10),
	TENDV NVARCHAR(150) NOT NULL,
	GIA FLOAT NOT NULL,
	SLTON INT,
	GHICHU NVARCHAR(150),
	FOREIGN KEY (MASANPHAM) REFERENCES DMSANPHAM(MA)
)
GO

CREATE TABLE DATDICHVUCT
(

	MAKHACHHANG VARCHAR(10) ,
	MADICHVU VARCHAR(10),
	SLDICHVU INT ,
	PRIMARY KEY (MAKHACHHANG, MADICHVU),
	FOREIGN KEY (MAKHACHHANG) REFERENCES DMKHACHHANG(MA),
	FOREIGN KEY (MADICHVU) REFERENCES DMDICHVU(MA)
)
GO
------------------------------------------

CREATE TABLE DMLOAIVTHH
(

	MA VARCHAR(10) PRIMARY KEY,
	TEN NVARCHAR(150)
)
GO

CREATE TABLE DMNHACUNGCAP
(
	
	MA VARCHAR(10) PRIMARY KEY,
	TEN NVARCHAR(150),
	DIACHI NVARCHAR(150),
	SDT VARCHAR(12),
	EMAIL VARCHAR(150),
	GHICHU NVARCHAR(150)
)
GO

CREATE TABLE DMVATTUHANGHOA
(
	
	MA VARCHAR(10) PRIMARY KEY,
	MASANPHAM VARCHAR(10),
	MALOAI VARCHAR(10),
	MANCC VARCHAR(10),
	TEN NVARCHAR(150),
	DVT VARCHAR(50),
	SLTON INT

	FOREIGN KEY (MALOAI) REFERENCES DMLOAIVTHH(MA),
	FOREIGN KEY (MANCC) REFERENCES DMNHACUNGCAP(MA),
	FOREIGN KEY (MASANPHAM) REFERENCES DMSANPHAM(MA)
)
GO


CREATE TABLE DATVATTUHANGHOACT
(
	
	MAVTHH VARCHAR(10),
	MAKHACHHANG VARCHAR(10),
	SLDAT INT

	FOREIGN KEY (MAVTHH) REFERENCES  DMVATTUHANGHOA(MA),
	FOREIGN KEY (MAKHACHHANG) REFERENCES DMKHACHHANG(MA)
)
GO

--------------------------------------------------

CREATE TABLE DMCHUCVU
(

	MA VARCHAR(10) PRIMARY KEY,
	TEN NVARCHAR(150)
)
GO
CREATE TABLE DMBOPHAN
(

	MA VARCHAR(10) PRIMARY KEY,
	TEN NVARCHAR(150)
)
GO

CREATE TABLE DMNHANVIEN
(

	MA VARCHAR(10) PRIMARY KEY,
	MACHUCVU VARCHAR(10),
	MABOPHAN VARCHAR(10),
	TEN NVARCHAR(150),
	GIOITINH NVARCHAR(5),
	NGAYSINH DATETIME2 ,
	DIACHI NVARCHAR(150) ,
	SDT NCHAR(10),
	EMAIL NVARCHAR(150) ,
	GHICHU NVARCHAR(150),
	FOREIGN KEY (MACHUCVU) REFERENCES DMCHUCVU(MA),
	FOREIGN KEY (MABOPHAN) REFERENCES DMBOPHAN(MA)
)
GO


CREATE TABLE DMTAIKHOAN
(
	
	MANHANVIEN VARCHAR(10) ,
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(50),
	FOREIGN KEY (MANHANVIEN)REFERENCES DMNHANVIEN(MA),
)
GO

----------------------------------------------------------------

CREATE TABLE DMHOADON
(
	
	MA VARCHAR(10) PRIMARY KEY,
	MANHANVIEN VARCHAR(10),
	MAKHACHHANG VARCHAR(10),
	MAGIAPHONG VARCHAR(10),
	NGAYLAP DATETIME2,

	FOREIGN KEY (MANHANVIEN) REFERENCES DMNHANVIEN(MA),
	FOREIGN KEY (MAKHACHHANG) REFERENCES DMKHACHHANG(MA),
	FOREIGN KEY (MAGIAPHONG) REFERENCES DMGIAPHONG(MA)
)
GO

CREATE TABLE HOADONCT
(
	
	MAHOADON VARCHAR(10),
	MASANPHAM VARCHAR(10),
	SL INT,
	PRIMARY KEY (MAHOADON,MASANPHAM),
	FOREIGN KEY (MAHOADON) REFERENCES DMHOADON(MA),
	FOREIGN KEY (MASANPHAM) REFERENCES DMSANPHAM(MA),
)
GO




----------------------------------------
CREATE TABLE DMPHIEUNHAP
(

	MA VARCHAR(10) PRIMARY KEY,
	MANHANVIEN VARCHAR(10),
	MANCC VARCHAR(10),
	NGAYLAP DATETIME2,
	

	FOREIGN KEY (MANHANVIEN) REFERENCES DMNHANVIEN(MA),
	FOREIGN KEY (MANCC) REFERENCES DMNHACUNGCAP(MA)
)
GO

CREATE TABLE PHIEUNHAPCT
(
	MAPN VARCHAR(10),
	MAVTHH VARCHAR(10),
	GIA INT,
	SLNHAP INT
	PRIMARY KEY (MAPN, MAVTHH),
	FOREIGN KEY (MAPN) REFERENCES DMPHIEUNHAP(MA),
	FOREIGN KEY (MAVTHH) REFERENCES DMVATTUHANGHOA(MA),
)
GO













